[project]
name = "unused-lib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.7.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
