FROM python:3.12-slim AS builder

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY --from=ghcr.io/astral-sh/uv:0.4.12 /uv /bin/uv

WORKDIR /app

COPY uv.lock pyproject.toml .python-version /app/

RUN --mount=type=cache,target=/root/.cache/uv \
  uv sync --frozen --no-install-project --package app --no-install-workspace

COPY . .
RUN --mount=type=cache,target=/root/.cache/uv \
  uv sync --frozen --no-editable --package app

FROM python:3.12-slim AS runner
COPY --from=builder /app /app
WORKDIR /app/app

ENV PATH "/app/.venv/bin:$PATH"

CMD ["python", "hello.py"]