FROM python:3.12-slim AS builder

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY --from=ghcr.io/astral-sh/uv:0.4.12 /uv /bin/uv

WORKDIR /app

COPY /app/uv.lock /app/pyproject.toml /app/.python-version /app/app/

WORKDIR /app/app
RUN --mount=type=cache,target=/root/.cache/uv \
  uv sync --frozen --no-install-project --no-install-package lib

COPY . ..
RUN --mount=type=cache,target=/root/.cache/uv \
  uv sync --frozen --no-editable


FROM python:3.12-slim AS runner
WORKDIR /app
COPY --from=builder /app/app /app

ENV PATH "/app/.venv/bin:$PATH"

CMD ["python", "hello.py"]
