[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lib",
]

[tool.uv.sources]
lib = { path = "../lib", editable = true }
